# 0. CLEAN UP PRIOR VERSIONS OF SUGARIZER (NEEDS WORK!)

- name: Wipe /library/www/html/sugarizer* if installing sugarizer-1.0
  shell: "rm -rf {{ doc_root }}/sugarizer*"
  when: sugarizer_version == "sugarizer-1.0"

# 1. DOWNLOAD /opt/iiab/sugarizer

- name: Clone llaske/sugarizer ({{ sugarizer_git_version }}) from GitHub to /opt/iiab
  git:
    repo: https://github.com/llaske/sugarizer
    dest: "{{ sugarizer_location }}/{{ sugarizer_version }}"
    version: "{{ sugarizer_git_version }}"
    force: yes
    depth: 1
  when: internet_available

- name: Create symbolic link /opt/iiab/sugarizer -> /opt/iiab/{{ sugarizer_version }}
  file:
    src: "{{ sugarizer_location }}/{{ sugarizer_version }}"
    dest: "{{ sugarizer_location }}/sugarizer"
    state: link

# 2. DOWNLOAD /opt/iiab/sugarizer-server

# July 2018: http://download.iiab.io/packages/sugarizer-server-1.0.tar.gz
# was flawed, as documented at:
#    https://github.com/iiab/iiab/pull/814#issuecomment-404211098
# Versions of MongoDB, npm (& Node.js ?) matter!  Sugarizer 1.0 Context:
#    https://github.com/iiab/iiab/issues/798
# Going forward let's "git clone" IIAB's preferred versions, of sugarizer
# AND sugarizer-server, as specified in roles/sugarizer/defaults/main.yml

- name: Clone llaske/sugarizer-server ({{ sugarizer_server_git_version }}) from GitHub to /opt/iiab
  git:
    repo: https://github.com/llaske/sugarizer-server
    dest: "{{ sugarizer_location }}/{{ sugarizer_server_version }}"
    version: "{{ sugarizer_server_git_version }}"
    force: yes
    depth: 1
  when: internet_available

- name: Create symbolic link /opt/iiab/sugarizer-server -> /opt/iiab/{ sugarizer_server_version }}
  file:
    src: "{{ sugarizer_location }}/{{ sugarizer_server_version }}"
    dest: "{{ sugarizer_location }}/sugarizer-server"
    state: link

# 3. INSTALL A GOOD VERSION OF Node.js AND npm

# Both Raspbian and Debian 9 STILL need this approach as of July 2018,
# as documented at https://github.com/iiab/iiab/issues/798#issuecomment-404324530
- name: Set up Node.js 8.x apt sources (debuntu but avoid ubuntu-18)
  shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -
  when: internet_available and is_debuntu and not is_ubuntu_18

- name: Install latest Node.js which includes /usr/bin/npm (debuntu but avoid ubuntu-18)
  package:
    name: nodejs
    # name: nodejs=8.x
    state: latest
    # state: present
  when: internet_available and is_debuntu and not is_ubuntu_18

- name: Install Node.js and npm (ubuntu-18)
  package:
    name: "{{ item }}"
    state: latest
  when: internet_available and is_ubuntu_18
  with_items:
    - nodejs
    - npm

- name: Install npm (OS's other than debuntu)
  package:
    name: "{{ item }}"
    state: present
  when: internet_available and not is_debuntu
  with_items:
    - nodejs
    - npm

# 4. RUN "npm install" TO POPULATE ~35MB /opt/iiab/sugarizer-server/node_modules

# Re-running "npm install" fails on Raspbian 9 if not other OS's
- name: Check for /opt/iiab/{{ sugarizer_server_version }}/node_modules
  stat:
    path: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/node_modules"
  register: nmtest
  ignore_errors: true

- name: Set a flag to prevent re-running of "npm install"
  set_fact:
    node_modules_exists: True
  when: nmtest.stat is defined and nmtest.stat.exists

- name: Create the express framework for Node.js (OS's other than Fedora 18)
  shell: npm install
  args:
    chdir: "{{ sugarizer_location }}/{{  sugarizer_server_version }}"
    creates: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/node_modules"
    #creates: "{{ sugarizer_location }}/{{ sugarizer_server_version }}/server/node_modules"
  when: not is_F18 and not node_modules_exists

- name: Create the express framework for Node.js (Fedora 18)
  shell: npm install
  args:
    chdir: "{{ sugarizer_location }}/sugarizer/server"
  when: is_F18 and not node_modules_exists

# 5. PLACE CONFIG FILES

- name: Configure sugarizer.service (systemd), sugarizer.conf (Apache) and sugarizer.ini
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: 'sugarizer.service.j2', dest: '/etc/systemd/system/sugarizer.service', mode: '0644' }
    - { src: 'sugarizer.ini', dest: '{{ sugarizer_location }}/{{ sugarizer_server_version }}/env/sugarizer.ini', mode: '0644' }
    - { src: 'sugarizer.conf', dest: '/etc/apache2/sites-available', mode: '0644' }

- name: Create symlink for short URL http://box/sugarizer
  file:
    src: /etc/apache2/sites-available/sugarizer.conf
    dest: /etc/apache2/sites-enabled/sugarizer.conf
    state: link

# 6. RESTART/STOP SYSTEMD SERVICE

- name: Enable services (all OS's)
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: restarted
  with_items:
    - { name: mongodb }
    - { name: sugarizer }
  when: sugarizer_enabled

- name: Disable service (all OS's)
  service:
    name: "{{ item.name }}"
    enabled: no
    state: stopped
  with_items:
    - { name: sugarizer }
  when: not sugarizer_enabled

- name: Add 'sugarizer' to list of services at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: sugarizer
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: Sugarizer
    - option: description
      value: '"The Sugar Learning Platform began with the famous One Laptop Per Child project, written in Python. Sugarizer is the new HTML/JavaScript implementation of Sugar, usable in most all browsers."'
    - option: enabled
      value: "{{ sugarizer_enabled }}"
